// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnmjcfeamwuldvrdzfvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubWpjZmVhbXd1bGR2cmR6ZnZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Njg4NDYsImV4cCI6MjA2NzE0NDg0Nn0.5RFfQNkyAMyG99PZcGZHojAqXu0V_pH1jHd-92aWqSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});